language: swift
osx_image: xcode9

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
    
xcode_project: Memory.xcodeproj
xcode_scheme: MemoryTests
before_install:
  - echo -e "machine bitbucket.com\n  login ci-user\n  password $CI_USER_PASSWORD" > ~/.netrc
script:
  - fastlane test